# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  postgres-data:
    